name: Test CI

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
  push:
    branches:
      - develop
      - feature/*

jobs:
  continuous-integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [16.x],
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Check TSC
        run: yarn tsc

      - name: Check Lint
        run: yarn lint

      - name: Build
        run: yarn build:dev
